baseURL = 'https://www.dev.autsch.org'
title = 'Autsch'

disableKinds = ['taxonomy', 'taxonomyTerm']
enableRobotsTXT = true

[params]
baseDomain = 'dev.autsch.org'

[params.subdomains]
jitsi = 'hang'
jitsiKeycloak = 'login.hang'
